version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiram1414
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8020:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: leonardopellegrinoo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Super@3025
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
