version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiram1414
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

volumes:
  db-data:
