version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: userHiram
      POSTGRES_PASSWORD: hiram1414
      POSTGRES_DB: hiram1414
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - hiram-backend

volumes:
  db-data:

networks:
  hiram-backend:
